[workspace]
authors = ["LudoBroche <ludovic.broche@pm.me>"]
channels = ["conda-forge"]
name = "ewoksdraw"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = ">=3.14.6,<3.15"

[pypi-dependencies]
ewoksdraw = { path = ".", editable = true }

[tasks]
lint = { cmd = "ruff check --fix . && ruff format .", description = "Auto-fix Ruff lint issues, sort imports, and format Python code" }